name: S905D KERNEL 5.15.y

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
env:
  REPO_URL: https://github.com/unifreq/linux-5.15.y
  REPO_BRANCH: main
  BUILD_DIR: /tmp/kernel
  SERVERCHAN_SCKEY: true
  KVER: 5.15.y
  TOOLCHAIN: https://github.com/kissyouhunter/kernel_N1/releases/download/toolchain/gcc-linaro-11.2.1-2021.12-x86_64_aarch64-linux-gnu.tar.xz
jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
    - name: telegrame_bot
      run: |
        if [[ "${SERVERCHAN_SCKEY}" == "true" ]]; then
          curl -k --data chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" --data "text=ğŸ‰ ä¸»äººï¼š
          æ‚¨æ­£åœ¨ä½¿ç”¨kissyouhunterä»“åº“ç¼–è¯‘N1å†…æ ¸5.15.y,è¯·è€å¿ƒç­‰å¾…...... ğŸ˜‹" "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage"
        fi
        
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Host info
      run: |
        pwd
        ls -lah
        lscpu
        free -h
        df -h 
        
    - name: Installing requirements 
      run: |
        sudo apt-get update
        sudo apt-get install -y git fakeroot build-essential ncurses-dev xz-utils libssl-dev bc flex libelf-dev bison libncurses-dev autoconf dkms libudev-dev libpci-dev libiberty-dev u-boot-tools lzop
        
    - name: Clone repos
      run: |
        git clone $REPO_URL -b $REPO_BRANCH /tmp/kernel
        
    - name: Installing cross compile toolchain
      run: |
        cd /opt
        sudo wget $TOOLCHAIN
        sudo xz -d gcc-linaro-11.2.1-2021.12-x86_64_aarch64-linux-gnu.tar.xz
        sudo tar xf gcc-linaro-11.2.1-2021.12-x86_64_aarch64-linux-gnu.tar
        cd /tmp/kernel
        wget https://raw.githubusercontent.com/kissyouhunter/kernel_N1/main/files/5.15/set_clean
        wget https://raw.githubusercontent.com/kissyouhunter/kernel_N1/main/files/5.15/set_dtb
        wget https://raw.githubusercontent.com/kissyouhunter/kernel_N1/main/files/5.15/set_make
        wget https://raw.githubusercontent.com/kissyouhunter/kernel_N1/main/files/5.15/set_menuconfig
        chmod 755 set_*
        
    - name: Build Kernel  
      run: |
        cd /tmp/kernel
        cp $GITHUB_WORKSPACE/files/5.15/.config .config -v
        ./set_make
        
    - name: Organize files
      id: organize
      run: |
        cd /tmp && mv kernel $KVER
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
        echo "::set-output name=status::success"

    - name: Upload kernel directory
      uses: actions/upload-artifact@main
      if: steps.organize.outputs.status == 'success' && !cancelled()
      with:
        name: $KVER
        path: ${{ env.FIRMWARE }}
        
    - name: telegram_bot
      run: |
        if [[ "${SERVERCHAN_SCKEY}" == "true" ]]; then
          curl -k --data chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" --data "text=æˆ‘äº²çˆ±çš„âœ¨ä¸»äººâœ¨ï¼š
          æ‚¨ä½¿ç”¨kissyouhunterä»“åº“ç¼–è¯‘N1å†…æ ¸5.15.yé¡ºåˆ©ç¼–è¯‘å®Œæˆäº†ï¼ğŸ’" "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage"
        fi
